name: Release SIGAA-ME

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

jobs:
  build:
    name: Build & Release Windows
    runs-on: windows-latest

    permissions:
      contents: write # Needed to create releases

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder
        run: npm run release
